stages:
  - build
  - deploy
  - notify

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  REGISTRY_URL: oran1.ens.ad.etsmtl.ca:5000
  NAMESPACE: tuan
  IMAGE_NAME: $REGISTRY_URL/$NAMESPACE/$CI_PROJECT_NAME # Replace with your desired image name
  

build:
  image: quay.io/podman/stable
  stage: build
  tags:
    - oran-runner # Use your specific tag
  before_script:
    - podman info
    - id
  script:
    - sleep 5
    - mkdir -p /etc/containers/certs.d/$REGISTRY_URL
    - echo "$REGISTRY_CERTIFICATE" > /etc/containers/certs.d/$REGISTRY_URL/ca.crt
    - update-ca-trust
    - podman build . -t $IMAGE_NAME:$CI_COMMIT_SHA -t $IMAGE_NAME:latest
    - podman push $IMAGE_NAME:$CI_COMMIT_SHA
    - podman push $IMAGE_NAME:latest
  only:
    - tags
    - init


deploy:
  stage: deploy
  image: bitnami/kubectl:1.32.2
  tags:
    - oran-runner # Use your specific tag
  script:
    - export IMAGE_NAME=$IMAGE_NAME
    - export IMAGE_TAG=$CI_COMMIT_SHA
    - envsubst < helm/manifest.template.yaml > helm/manifest.yml
    - cat helm/manifest.yml
    - kubectl apply -f helm/manifest.yml -n $NAMESPACE
  only:
    - tags
    - init
  dependencies:
    - build
